SELECT P.NOME_COMPLETO AS nome, PF.CPF AS cpf, PJ.CNPJ AS cnpj, E.BAIRRO AS bairro, E.COD_UF, E.COD_MUNICIPIO , cd.descricao as municipio, es.nome as estado,
DECODE (PF.CPF, null, PJ.CNPJ, PF.CPF) as id
FROM CADASTRO.PESSOAS P
LEFT JOIN CADASTRO.PESSOA_FISICA PF ON PF.CODPESSOA = P.CODPESSOA
LEFT JOIN CADASTRO.PESSOA_JURIDICA PJ ON PJ.CODPESSOA = P.CODPESSOA
JOIN CADASTRO.ENDERECOS E ON E.CODPESSOA = P.CODPESSOA
JOIN PEMAZA.ags446 cd ON cd.cod_uf =  E.COD_UF and cd.cod_municipio = E.COD_MUNICIPIO  and cd.cod_pais = e.cod_pais
JOIN PEMAZA.ags043 es ON es.cod_uf =  cd.cod_uf
WHERE PF.CPF IS NOT NULL OR PJ.CNPJ IS NOT NULL